.TH man 1 "13.06.2022" "1306" "duzy.sh man page"
.SH NAME
duzy.sh - służy do uruchamiania demonów z katalogu .B /etc/init.d
.SH SYNOPSIS
.B duzy.sh
.PP
.BI duzy.sh " -o status"
.PP
.BI duzy.sh " -d apache2 -o start"
.SH DESCRIPTION
.B duzy.sh
wyświetla okno dialogowe zenity z listą demonów. Po dokonaniu wyboru przez użytkownika, jeśli nie została podana opcja -o, użytkownik wybiera z listy operację do wykonania, następnie podejmowana jest próba jej wykonania. Komunikaty są przekierowywane do okna informacyjnego zenity. Następnie wyświetlane jest początkowe okno.
 W przypadku anulowania lub zamknięcia okna wyboru, skrypt kończy działanie.
.SH OPTIONS
.TP
.BI -d " DEMON"
działanie skryptu w trybie tekstowym, wymaga użycia opcji 
.B -o,
której argument zostanie wykonany na 
.I demonie
.TP
.BI -o " start|stop|status"
ustawienie wybranej operacji na czas działania skryptu
.TP
.B -v
wyświetla wersję skryptu
.TP
.B -h
wyświetla pomoc
.SH BUGS
Brak znanych błędów.
.SH REPORTING BUGS
Błędy można zgłaszać na 
.UR https://github.com/kobryl/duzy_skrypt/issues
github issues
.UE "."
.SH AUTHOR
Konrad Bryłowski, 188577
.SH SEE ALSO
.BR systemctl (1)
